version: "3.9"

services:
  app:
    build:
      context: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: myapp_db
      JWT_SECRET: "your_jwt_secret"
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    container_name: myapp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
